### ISSUE TITLE
wait for transaction function -> Exception 

### ISSUE THREAD

**Issue by alice010101** [Lutwidse/dexbot-aptos#3]
`Exception: {"version":"8394226","hash":"0xb71cd6d9b7464922a3229f3e24d0164415154a94e323e2018652d482bc7fafb4","state_change_hash":"0x48456306f03800c27fa721023ade600dc9b92bf0c399824ebe2425f6762690c0","event_root_hash":"0x414343554d554c41544f525f504c414345484f4c4445525f4841534800000000","state_checkpoint_hash":null,"gas_used":"1101","success":false,"vm_status":"Move abort in 0x8980e4be64b163f08a7511131606ee2bc91fefe23f8f53f5b955e98fa7ac2341::factory: `0x3","accumulator_root_hash":"0x21b2cf96c94f89e8d01ef133eb476faeec1b3ed8c491485ffb87590aa524c069","changes":[{"address":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","state_key_hash":"0x0d38095573da3baae854a4375d4234b4688a07a4791350b6f3c57255fab21f6c","data":{"type":"0x1::coin::CoinStore<0x1::aptos_coin::AptosCoin>","data":{"coin":{"value":"4889900"},"deposit_events":{"counter":"1","guid":{"id":{"addr":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","creation_num":"2"}}},"frozen":false,"withdraw_events":{"counter":"0","guid":{"id":{"addr":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","creation_num":"3"}}}}},"type":"write_resource"},{"address":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","state_key_hash":"0x486d6402948406b012a45a054861d1b81e16690fa8f06c654bd520a136953d2c","data":{"type":"0x1::account::Account","data":{"authentication_key":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","coin_register_events":{"counter":"1","guid":{"id":{"addr":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","creation_num":"0"}}},"guid_creation_num":"4","key_rotation_events":{"counter":"0","guid":{"id":{"addr":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","creation_num":"1"}}},"rotation_capability_offer":{"for":{"vec":[]}},"sequence_number":"1","signer_capability_offer":{"for":{"vec":[]}}}},"type":"write_resource"},{"state_key_hash":"0x6e4b28d40f98a106a65163530924c0dcb40c1349d3aa915d108b4d6cfc1ddb19","handle":"0x1b854694ae746cdbd8d44186ca4929b2b337df21d1c74633be19b2710552fdca","key":"0x0619dc29a0aac8fa146714058e8dd6d2d0f3bdf5f6331907bf91f3acd81e6935","value":"0xace11f7fd7cd63010000000000000000","data":null,"type":"write_table_item"}],"sender":"0xaee20e26a1d9115932f5415fe571e394248de252c2114110b9df20c55506d333","sequence_number":"0","max_gas_amount":"3000","gas_unit_price":"100","expiration_timestamp_secs":"1666455138","payload":{"function":"0x8980e4be64b163f08a7511131606ee2bc91fefe23f8f53f5b955e98fa7ac2341::factory::mint_with_quantity","type_arguments":[],"arguments":["2"],"type":"entry_function_payload"},"signature":{"public_key":"0x6a5e900e221b5b6690c1215a8012aaceb7207a849fb33a5a300d0c1fca2865b8","signature":"0x2dac0a3d9eea82ee040c87b60ee761dc7fc1baeabcc312d1122cfcf4a412e3235cfd3e9c13333138589c49ed484c873cbb2237ae07195641a5c503d860746509","type":"ed25519_signature"},"events":[],"timestamp":"1666454539880238","type":"user_transaction"}` - 0xb71cd6d9b7464922a3229f3e24d0164415154a94e323e2018652d482bc7fafb4`

**Comment by lutwidse** [comment]
The function, module, and arguments are not the same on every mint.
change them with your own research.
